# YAML files can be merged
# using production ready external tools

---  # take on step definition
tool: innovus
step: place

reqires:  # requires this variables to be described and defined
  - [fp_def, fp]
  - lef
  - lib
  - run_dir
  - report_dir
  - out_dir
  - tool_path

inline:  # generated and unique for each run
  - script_path

provides:
  place.db

variables:  # will be put under corresponding namespace
  power_effort:
    reqired: true
    check_type: is_set
    default:
    value_list: [low, medium, high]

run_commands: |
  /path/to/tool -script $

body: |
  namespace import flow::innovus::place
  this is tcl text
  with commands you need
  that can use variables
  for example $power_effort

---  # configuration setup
variables:
  lef:
    required: true
    check_type: crc32

  lib:
    required: true
    check_type: crc32

---  # configuration

lib:
  - /path/ss.lib
  - /path/ff.lib
  - /path/tt.lib

lef:
  - /path/ss.lef
  - /path/ff.lef
  - /path/tt.lef

report_dir: /path/to/report/dir

---  # configuration block

lib:
  - /path/blk/macro.lib
  - /path/blk/mem.lib
...
